---

# Configuration file for vorne control
# Can be used to set IP, Default Ideal Times, Downtime Multipliers, and more
# Workstation name
workstation: "7100"

# Ip Address of scoreboard
ipAddress: "10.19.12.21"

# Debug mode - set true to enable enhanced console logging
debug_mode: False

# Keylogger mode - set true to enable SN detection via key input
keylogger_mode: True

# Default Cycle Time (minutes)
default_cycle_time: 0.75

# Default downtime threshold multiplier
# DT Threshold = default_cycle_time * downtime_multiplier
downtime_multiplier: 10

# Prevent duplicate serial numbers from being counted
duplicate_serial_prevention: True

### Browser Path
# Chrome
# browserPath: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"
# IE
browserPath: "C:/Program Files/Internet Explorer/iexplore.exe"

# CSV Run times file path
time_data_file: "G:/ZBrock/Vorne/Run_Times_12_1_2021.csv"

# Toggle whether the program should attempt to lookup standard run times
# If set to false, uses default times
lookup_times: True

### Cycle time adjustments
# Factor for adjusting the ideal time found in oracle
# If they are by default too high, multiply by a number < 1 (i.e. 0.9 for 10% reduction in ideal times)
# If they are by default too low, multiply by a number > 1  (i.e. 1.1 for a 10% increase in ideal times)
ideal_time_fudge_factor: 0.8

# Factor for adjusting the ideal time to an associated takt time
### takt_time = std_hours_in / team_size * ideal_time_fudge_factor * takt_time_factor
takt_time_factor: 1

# Minimum team count for efficiency calculations
minimum_team_count: 12